import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    username:{
        type:String,
        required:true,
        unique:true
    },
    email:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true,
    },
    profilePic:{
        type:String,
        default:'https://cdn-icons-png.flaticon.com/512/3177/3177440.png'
    },
    bio:{
        type:String,
        default:''
    },
    gender:{
        type:String,
        enum:['Male','Female','Other']
    },
    followers:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    following:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    posts:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Post"
        }
    ],
    bookmarks:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Post"
        }
    ],
    friends:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    groupJoined:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Group"
        }
    ],  
    notifications:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Notification"
        }
    ]
},{timestamps:true})

export const User = mongoose.model('User',userSchema);